### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by josiesajbel** [UW-Macrostrat/gplates-reconstruct#2]
I tried to transfer a geoJSON file using the "reconstruct an entire file" code and it's not working. Can anyone tell why I got the error that my "argument list is too long"?

![screen shot 2016-08-10 at 4 02 11 pm](https://cloud.githubusercontent.com/assets/19711083/17570928/fb35eeb2-5f13-11e6-9d86-71b26812cd5f.png)

**Comment by jczaplew** [comment]
That happens when the input GeoJSON file is too big to be POST-ed. As a workaround, you can use this script I wrote - https://gist.github.com/jczaplew/1d313c6ffcbf599da4e13229ef44e791
