### ISSUE TITLE
Holocene rotations should return modern coordinates

### ISSUE THREAD

**Issue by aazaff** [UW-Macrostrat/gplates-reconstruct#5]
In reference to paleobiodb/pbdb-new#11, the data service should return back modern coordinates as part of the GPlates service for Holocene rotations.

**Comment by jczaplew** [comment]
Could you please provide an example of this?

**Comment by aazaff** [comment]
Perhaps ask @markuhen in the original thread. I don't know what data he was
looking at.

**Comment by jczaplew** [comment]
There is not a query that produces this behavior on that thread. Once a test case can be provided I can dig into it.

**Comment by markuhen** [comment]
It looks like this is just the same bug I reported before. There are large swaths of Holocene occurrences in this download, but there are other Holocene occurrences that are reporting paleocoordinates just fine. I'm pasting the query below, but again, this seems like the same problem reported elsewhere, so I'm going to close this thread.

https://paleobiodb.org/data1.2/occs/list.csv?datainfo&rowcount&base_name=Pinnipedimorpha&idqual=certain&interval=Quaternary&private&show=full,acconly

**Comment by markuhen** [comment]
Apparently, I don't have the power to close threads, so if you guys agree this isn't a separate issue, feel free to close it! Thanks.
